version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /yaml.novaextension
    schedule:
      interval: weekly
